[package]
authors = ["Brooks Patton <brooks@brookzerker.com>"]
edition = "2018"
name = "jungle"
version = "0.1.0"

[dependencies]
eyre = "0.6.3"
ggez = "0.5.1"
rand = "0.7.3"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0.22"
