name: Rust

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Update
        run: sudo apt-get update
      - name: Install Packages
        run: sudo apt-get install -y libasound2-dev libudev-dev pkg-config jq
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Check Clippy
        run: cargo clippy -- -D clippy::all
      - name: Test
        run: cargo test ci_test
      - name: Build
        run: cargo build --release
      - name: package
        run: mkdir dist && zip -r dist/jungle_game resources target/release/jungle
      -name: set version
        run: cargo metadata --no-deps --format-version 1 | jq '.packages[0].version' > dist/version
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-1" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository
          DEST_DIR: "jungle"
